-- NESTA — alimentation prospection vague 2 : Laval + Couronne Nord (2026-09-28).
-- 21 promoteurs vérifiés par recherche web (sites officiels des projets/promoteurs).
-- Contacts PUBLICS uniquement. Aucun promoteur contacté à ce stade.
-- ATTENTION : la table n'a pas de contrainte d'unicité — vérifier le compte
-- avant exécution (select count(*) from public.prospects) pour éviter les doublons.
-- Les cas marqués « À VALIDER » dans les notes méritent une vérification manuelle
-- avant tout envoi (courriels incomplets, projets peut-être épuisés).

insert into public.prospects
  (company_name, contact_name, email, phone, website, project_name, project_location, project_type, status, source, notes)
values
  -- Zone Blainville / Mirabel / Saint-Eustache
  ('GBD Construction (Gestion Benoît Dumoulin)', 'Alain Brasseur', 'info@gbdconstruction.ca', '450-472-6303', 'https://gestionbenoitdumoulin.com', 'Albatros ; Le Faubourg Ste-Marthe', 'Saint-Eustache ; Sainte-Marthe-sur-le-Lac', 'Unifamiliales / Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Excellent fit : plusieurs gros projets actifs, bureau des ventes ouvert. Courriel à valider (source répertoire).'),
  ('Le Groupe Platinum', null, null, '450-434-0090', 'https://legroupeplatinum.com', 'Le Quartier Chambéry (condos dès 329 000 $)', 'Blainville', 'Condos / Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Promoteur blainvillois actif (30+ ans), projet condo en vente.'),
  ('Groupe 4M', 'Dave Auger', null, '450-312-1170', 'https://groupe4m.com', 'Harmonie St-Canut (70 maisons de ville)', 'Mirabel', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Projet vérifié sur le site officiel, numéro de ventes actif.'),
  ('Construction Voyer', 'Normand Bergeron', null, '450-963-8300 (poste 554)', 'https://voyer.ca', 'Les Villas de La Cité de Mirabel (dernière phase, 68 maisons de ville Novoclimat dès 585 000 $)', 'Mirabel', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Projet « prêt à habiter », phases finales à écouler. Même promoteur que Voyer (Laval).'),
  ('Skyblü Condos (Ray Junior Courtemanche)', null, 'vente@skyblucondos.com', '514-929-7766', 'https://skyblucondos.com', 'Skyblü — 3 tours de 15 étages à Cité Mirabel (phases 1-2 dispo, phase 3 en prévente)', 'Mirabel', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Projet d''envergure, ventes actives + prévente en cours.'),
  -- Zone Laval
  ('Urbania', 'Équipe des ventes U-Bahn', 'info@u-bahn.ca', '450 497-0144', 'https://u-bahn.condourbania.com/', 'U-Bahn (phase U1)', 'Laval-des-Rapides', 'Condos neufs', 'a_contacter', 'Recherche web sept. 2026', 'Occupation nov. 2026 ; disponibilités affichées sur le site officiel.'),
  ('Groupe TRÉMÄ', null, null, '514 239-2224', 'https://quartiermetta.com', 'Quartier Metta', 'Sainte-Dorothée, Laval', 'Maisons de ville / unifamiliales', 'a_contacter', 'Recherche web sept. 2026', 'Près du REM ; maisons disponibles à l''achat. Même promoteur que Quartier Montmartre (Saint-Jérôme).'),
  ('Groupe Pentian', null, null, null, 'https://pentian.ca/', 'Domaine Islesmère (dernière phase, 15 lots)', 'Sainte-Dorothée, Laval', 'Unifamiliales de prestige', 'a_contacter', 'Recherche web sept. 2026', 'À VALIDER : site officiel mentionne livraison été 2022, lots peut-être épuisés.'),
  ('Aldo Construction', 'Alessandra Catalogna', 'info@aldoconstruction.ca', '514-366-5000', 'https://aldoconstruction.ca', 'Le Mosaic (phase 4, 48 unités dès 609 500 $)', 'Auteuil, Laval', 'Maisons de ville neuves', 'a_contacter', 'Recherche web sept. 2026', 'Disponibilité confirmée par répertoires professionnels.'),
  ('Groupe Alta-Socam', null, null, '450 682-0220', 'https://www.condosviva.com', 'SUMUM phase 6 / VIVA phase 7 (3½ dès 333 293 $)', 'Chomedey, Laval', 'Condos neufs', 'a_contacter', 'Recherche web sept. 2026', 'Projet de 750+ unités près de Centropolis.'),
  ('Voyer', 'J. Copan', 'jcopan@voyer.ca', '450 963-8300 poste 555', 'https://www.voyer.ca', 'Habitat Veridis (unifamiliales ~1 049 900 $, garantie GCR)', 'Auteuil, Laval', 'Unifamiliales neuves', 'a_contacter', 'Recherche web sept. 2026', 'À VÉRIFIER : projet non retrouvé sur voyer.ca. Même promoteur que Construction Voyer (Mirabel).'),
  -- Zone Saint-Jérôme / Laurentides
  ('Domicil', null, null, '514 374-4444', 'http://www.lenorden.com/', 'Le Norden (maisons en construction + terrains, liste de prix 2026)', 'Saint-Sauveur', 'Maisons prestige / jumelées', 'a_contacter', 'Recherche web sept. 2026', 'Projet actif au Sommet Saint-Sauveur, bon fit Passeport haut de gamme.'),
  ('Constructions Cousineau', null, 'vente@unemaisonneuve.com', '514 291-8983', 'http://www.havredesfalaises.com/', 'Havre des Falaises (maisons modèles à visiter)', 'Prévost', 'Unifamiliales neuves clé en main', 'a_contacter', 'Recherche web sept. 2026', 'Annonces actives vérifiées, volume compatible avec l''offre Nesta.'),
  ('Groupe Pro-Fab', null, 'info@profab.ca', '450 302-2622', 'https://www.profab.ca/', 'ProFab Saint-Lin–Laurentides (150+ modèles)', 'Saint-Lin–Laurentides', 'Maisons usinées neuves', 'a_contacter', 'Recherche web sept. 2026', 'Constructeur à volume élevé, idéal pour services récurrents.'),
  ('Invesco Habitation', null, null, '450-226-3959', 'https://www.invescohabitation.ca/', 'Belle Plagne et autres terrains-projets', 'Saint-Sauveur', 'Terrains + construction clé en main', 'a_contacter', 'Recherche web sept. 2026', 'Inventaire actif de terrains et constructions à Saint-Sauveur.'),
  ('Groupe TRÉMÄ', null, null, '514-817-0254 (à confirmer)', 'http://www.lequartiermontmartre.com/', 'Quartier Montmartre', 'Saint-Jérôme', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'FAIBLE PRIORITÉ : dernière phase, un seul condo restant. Même promoteur que Quartier Metta (Laval).'),
  -- Zone Terrebonne / Mascouche / L'Assomption
  ('Groupe EVEX', null, null, '514-884-3839', 'https://groupeevex.com', 'Domaine Achigan (23 maisons de ville)', 'L''Assomption', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', '23 unités affichées « disponibles dès maintenant » sur le site officiel.'),
  ('GBD Construction', 'Valérie Dumoulin', null, '450-472-6303', 'https://www.gestionbenoitdumoulin.com', 'Le Square Saint-François (~100 maisons de ville clé en main)', 'Terrebonne', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Bureau des ventes actif, interlocutrice nommée. Même promoteur que GBD (Saint-Eustache).'),
  ('Rheault Construction', 'Amélie Rheault', 'rheaultreseau@constructionsergerheault', '514-773-7239', 'http://www.constructionsergerheault.com', 'Boisé de la Seigneurie (12 terrains restants, 2 modèles prêts ~1er oct. 2026)', 'Mascouche', 'Unifamiliales neuves', 'a_contacter', 'Recherche web sept. 2026', 'À VALIDER : courriel possiblement tronqué (suffixe manquant) — vérification manuelle recommandée.'),
  ('Constructions Martin Cadieux et Fils', 'Martin Cadieux', null, '514-893-6170', null, 'Les Jardins du Coteau (triplex 5½ dès 615 000 $)', 'Mascouche', 'Triplex neufs', 'a_contacter', 'Recherche web sept. 2026', 'Pas de site web officiel trouvé ; fiche Guide Immo active.'),
  ('Madeco', null, null, '450-686-4006', 'https://madeco.ca', 'Grandeur Nature, Urbanova (livraison 2026, dès 1 065 449 $)', 'Terrebonne', 'Unifamiliales de prestige', 'a_contacter', 'Recherche web sept. 2026', 'Promoteur établi depuis 1996.');
