-- NESTA — alimentation initiale de la prospection (2026-09-28).
-- 14 promoteurs vérifiés par recherche web (sites officiels des projets).
-- Contacts PUBLICS uniquement. Aucun promoteur contacté à ce stade.

insert into public.prospects
  (company_name, contact_name, email, phone, website, project_name, project_location, project_type, status, source, notes)
values
  ('Groupe Kevlar', null, null, '514-400-0280', 'https://gatsbycondos.com', 'Gatsby Condominiums', 'Centre-ville, 1200 rue Drummond', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Prioritaire : promoteur à projet unique, ventes actives (soirées privées). Fit pilote idéal.'),
  ('Mondev', null, null, '514-447-7830', 'https://mondev.ca', 'Florence ; 367 des Pins ; 5550 Saint-Patrick', 'Ville-Marie, Plateau-Mont-Royal, Sud-Ouest', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Prioritaire : plusieurs projets actifs + inventaire futur (5550 Saint-Patrick, occupation 2028). Autre ligne : 514-700-6529 (367 des Pins).'),
  ('Groupe Quorum', null, null, '438-375-9001', 'https://galdin.ca', 'Galdín', 'Saint-Henri, bord du canal Lachine', 'Condos + maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Prioritaire : inventaire en livraison, prix publics affichés. Ligne ventes : 514-822-2888.'),
  ('Groupe HD', 'Isabelle Drolet', null, '514-775-4758', 'https://groupehdimmobilier.ca', 'Laurea', 'Mercier–Hochelaga-Maisonneuve', 'Condos + maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Condos dès 288 300 $. Courriel à reprendre sur le site officiel.'),
  ('Samcon', null, null, '+1 514-562-1404', 'https://samcon.ca/fr/marquette', 'Terrasses Marquette', 'Rosemont–La Petite-Patrie, 6836–6852 rue Marquette', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Condos 2–3 ch. dès 469 000 $ + taxes, occupation sept. 2026.'),
  ('Bertone', null, 'info@bertone.ca', '1-866-400-4576', 'https://bertone.ca/fr/projects/moden', 'Le Moden', 'Métro Frontenac, Ville-Marie Est', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Occupation immédiate, promotion en cours sur unités restantes. Autre ligne : (514) 747-1696.'),
  ('Rachel Julien', null, 'info@canoemtl.com', '514-849-7334', 'https://canoemtl.com', 'Canoë — Phase 2', 'Hochelaga, 4500 rue Hochelaga', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Condos dès 319 000 $. Phase 1 = locatifs (exclue).'),
  ('Groupe DACA', null, 'administration@groupedaca.com', '+1 (514) 393-8700', 'https://groupedaca.ca/condominiums-a-vendre', 'ONE Viger', 'Centre-ville, 1 av. Viger O.', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Dernières unités du promoteur. Attention : les annonces Centris/REMAX au nom du projet sont des reventes de particuliers.'),
  ('Groupe Mathieu', 'Sylvye Lelièvre', null, '450 435-6239', 'https://groupemathieu.com/projets', 'Projet Charme ; VËE ; Noüvo District', 'Blainville, Laval (Auteuil), Terrebonne (Urbanova)', 'Maisons de ville + condos', 'a_contacter', 'Recherche web sept. 2026', 'Couronne Nord. Bureau de vente projet : 514 241-1667.'),
  ('Omnia Technologies', null, null, '450-419-5353', null, 'Imperia Condominiums ; Enticy ; Théâtre Snowdon', 'Ville-Marie, CDN–NDG', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Imperia et Snowdon en occupation immédiate. Contact ventes officiel à reprendre sur le site du promoteur.'),
  ('LSR Gesdev', null, null, '+1 450-923-2400', 'https://viclambert.ca', 'Vic&Lambert', 'Saint-Lambert, 295 rue Riverside', 'Condos', 'a_contacter', 'Recherche web sept. 2026', '42 condos + 9 penthouses, bureau de vente actif.'),
  ('Cogir / TAK Prestige', null, 'info@takprestige.com', '514-900-3434', 'https://takprestige.com', 'TAK Prestige, phase 7B', 'Rosemont-Angus', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', '14 maisons de ville, dernière phase, promotion en cours.'),
  ('Devimco', null, null, null, 'https://devimco.com/projets-immobiliers-residentiels-achat', 'Palma ; Wellington sur le Bassin ; Auguste/Louis', 'Brossard, Griffintown, Quartier des lumières', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Secondaire : grand acteur, plus difficile à convertir. Contact ventes à reprendre sur devimco.com.'),
  ('Groupe Prével', null, null, null, null, '21e arrondissement (phase 5)', 'Est de Montréal', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Secondaire : grand acteur. Statut en vente à re-vérifier sur le site officiel.');
