-- NESTA — alimentation prospection vague 2 (fusionnée) : Laval + Couronne Nord (2026-09-28).
-- 18 entreprises uniques (21 lignes de recherche, 3 doublons fusionnés : GBD, Voyer, TRÉMÄ).
-- Contacts PUBLICS uniquement. Aucun promoteur contacté à ce stade.
-- Statuts : a_contacter = prêt ; a_reverifier = vérifier manuellement avant tout envoi.

insert into public.prospects
  (company_name, contact_name, email, phone, website, project_name, project_location, project_type, status, source, notes)
values
  ('GBD Construction (Gestion Benoît Dumoulin)', 'Alain Brasseur (St-Eustache) ; Valérie Dumoulin (Terrebonne)', 'info@gbdconstruction.ca', '450-472-6303', 'https://gestionbenoitdumoulin.com', 'Albatros ; Le Faubourg Ste-Marthe ; Le Square Saint-François (~100 maisons de ville clé en main)', 'Saint-Eustache ; Sainte-Marthe-sur-le-Lac ; Terrebonne', 'Unifamiliales / Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Plusieurs gros projets actifs, bureaux des ventes ouverts. Courriel info@gbdconstruction.ca à valider (source répertoire).'),
  ('Le Groupe Platinum', null, null, '450-434-0090', 'https://legroupeplatinum.com', 'Le Quartier Chambéry (condos dès 329 000 $)', 'Blainville', 'Condos / Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Promoteur blainvillois actif (30+ ans), projet condo en vente.'),
  ('Groupe 4M', 'Dave Auger', null, '450-312-1170', 'https://groupe4m.com', 'Harmonie St-Canut (70 maisons de ville)', 'Mirabel', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', 'Projet vérifié sur le site officiel, numéro de ventes actif.'),
  ('Construction Voyer', 'Normand Bergeron (Mirabel) ; J. Copan (Laval)', 'jcopan@voyer.ca', '450-963-8300', 'https://voyer.ca', 'Les Villas de La Cité de Mirabel (dernière phase, 68 maisons de ville Novoclimat dès 585 000 $) ; Habitat Veridis (unifamiliales ~1 049 900 $)', 'Mirabel ; Auteuil, Laval', 'Maisons de ville / Unifamiliales neuves', 'a_contacter', 'Recherche web sept. 2026', 'Phases finales à écouler à Mirabel. À vérifier : projet Habitat Veridis (Laval) non retrouvé sur voyer.ca.'),
  ('Skyblü Condos (Ray Junior Courtemanche)', null, 'vente@skyblucondos.com', '514-929-7766', 'https://skyblucondos.com', 'Skyblü — 3 tours de 15 étages à Cité Mirabel (phases 1-2 dispo, phase 3 en prévente)', 'Mirabel', 'Condos', 'a_contacter', 'Recherche web sept. 2026', 'Projet d''envergure, ventes actives + prévente en cours.'),
  ('Urbania', 'Équipe des ventes U-Bahn', 'info@u-bahn.ca', '450 497-0144', 'https://u-bahn.condourbania.com/', 'U-Bahn (phase U1)', 'Laval-des-Rapides', 'Condos neufs', 'a_contacter', 'Recherche web sept. 2026', 'Occupation nov. 2026 ; disponibilités affichées sur le site officiel.'),
  ('Groupe TRÉMÄ', null, null, '514 239-2224', 'https://quartiermetta.com', 'Quartier Metta (Sainte-Dorothée, Laval) ; Quartier Montmartre (Saint-Jérôme)', 'Laval ; Saint-Jérôme', 'Maisons de ville / unifamiliales / Condos', 'a_contacter', 'Recherche web sept. 2026', 'Près du REM ; maisons disponibles à l''achat. Faible priorité sur Montmartre (dernière phase, 1 condo restant ; tél. 514-817-0254 à confirmer).'),
  ('Groupe Pentian', null, null, null, 'https://pentian.ca/', 'Domaine Islesmère (dernière phase, 15 lots)', 'Sainte-Dorothée, Laval', 'Unifamiliales de prestige', 'a_reverifier', 'Recherche web sept. 2026', 'À valider : site officiel mentionne livraison été 2022, lots peut-être épuisés.'),
  ('Aldo Construction', 'Alessandra Catalogna', 'info@aldoconstruction.ca', '514-366-5000', 'https://aldoconstruction.ca', 'Le Mosaic (phase 4, 48 unités dès 609 500 $)', 'Auteuil, Laval', 'Maisons de ville neuves', 'a_contacter', 'Recherche web sept. 2026', 'Disponibilité confirmée par répertoires professionnels.'),
  ('Groupe Alta-Socam', null, null, '450 682-0220', 'https://www.condosviva.com', 'SUMUM phase 6 / VIVA phase 7 (3½ dès 333 293 $)', 'Chomedey, Laval', 'Condos neufs', 'a_contacter', 'Recherche web sept. 2026', 'Projet de 750+ unités près de Centropolis.'),
  ('Domicil', null, null, '514 374-4444', 'http://www.lenorden.com/', 'Le Norden (maisons en construction + terrains, liste de prix 2026)', 'Saint-Sauveur', 'Maisons prestige / jumelées', 'a_contacter', 'Recherche web sept. 2026', 'Projet actif au Sommet Saint-Sauveur, bon fit Passeport haut de gamme.'),
  ('Constructions Cousineau', null, 'vente@unemaisonneuve.com', '514 291-8983', 'http://www.havredesfalaises.com/', 'Havre des Falaises (maisons modèles à visiter)', 'Prévost', 'Unifamiliales neuves clé en main', 'a_contacter', 'Recherche web sept. 2026', 'Annonces actives vérifiées, volume compatible avec l''offre Nesta.'),
  ('Groupe Pro-Fab', null, 'info@profab.ca', '450 302-2622', 'https://www.profab.ca/', 'ProFab Saint-Lin–Laurentides (150+ modèles)', 'Saint-Lin–Laurentides', 'Maisons usinées neuves', 'a_contacter', 'Recherche web sept. 2026', 'Constructeur à volume élevé, idéal pour services récurrents.'),
  ('Invesco Habitation', null, null, '450-226-3959', 'https://www.invescohabitation.ca/', 'Belle Plagne et autres terrains-projets', 'Saint-Sauveur', 'Terrains + construction clé en main', 'a_contacter', 'Recherche web sept. 2026', 'Inventaire actif de terrains et constructions à Saint-Sauveur.'),
  ('Groupe EVEX', null, null, '514-884-3839', 'https://groupeevex.com', 'Domaine Achigan (23 maisons de ville)', 'L''Assomption', 'Maisons de ville', 'a_contacter', 'Recherche web sept. 2026', '23 unités affichées « disponibles dès maintenant » sur le site officiel.'),
  ('Rheault Construction', 'Amélie Rheault', null, '514-773-7239', 'http://www.constructionsergerheault.com', 'Boisé de la Seigneurie (12 terrains restants, 2 modèles prêts ~1er oct. 2026)', 'Mascouche', 'Unifamiliales neuves', 'a_reverifier', 'Recherche web sept. 2026', 'Courriel possiblement tronqué (suffixe manquant) — à vérifier manuellement avant tout envoi.'),
  ('Constructions Martin Cadieux et Fils', 'Martin Cadieux', null, '514-893-6170', null, 'Les Jardins du Coteau (triplex 5½ dès 615 000 $)', 'Mascouche', 'Triplex neufs', 'a_reverifier', 'Recherche web sept. 2026', 'Pas de site web officiel trouvé ; fiche Guide Immo active — à valider.'),
  ('Madeco', null, null, '450-686-4006', 'https://madeco.ca', 'Grandeur Nature, Urbanova (livraison 2026, dès 1 065 449 $)', 'Terrebonne', 'Unifamiliales de prestige', 'a_contacter', 'Recherche web sept. 2026', 'Promoteur établi depuis 1996.');
